# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.15.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.15.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/jingxuandeng/phd/KRG/research/diss_pre_ML/fracture

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/jingxuandeng/phd/KRG/research/diss_pre_ML/fracture

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.15.2/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.15.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jingxuandeng/phd/KRG/research/diss_pre_ML/fracture/CMakeFiles /Users/jingxuandeng/phd/KRG/research/diss_pre_ML/fracture/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jingxuandeng/phd/KRG/research/diss_pre_ML/fracture/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named karst

# Build rule for target.
karst: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 karst
.PHONY : karst

# fast build rule for target.
karst/fast:
	$(MAKE) -f CMakeFiles/karst.dir/build.make CMakeFiles/karst.dir/build
.PHONY : karst/fast

src/analysis.o: src/analysis.cc.o

.PHONY : src/analysis.o

# target to build an object file
src/analysis.cc.o:
	$(MAKE) -f CMakeFiles/karst.dir/build.make CMakeFiles/karst.dir/src/analysis.cc.o
.PHONY : src/analysis.cc.o

src/analysis.i: src/analysis.cc.i

.PHONY : src/analysis.i

# target to preprocess a source file
src/analysis.cc.i:
	$(MAKE) -f CMakeFiles/karst.dir/build.make CMakeFiles/karst.dir/src/analysis.cc.i
.PHONY : src/analysis.cc.i

src/analysis.s: src/analysis.cc.s

.PHONY : src/analysis.s

# target to generate assembly for a file
src/analysis.cc.s:
	$(MAKE) -f CMakeFiles/karst.dir/build.make CMakeFiles/karst.dir/src/analysis.cc.s
.PHONY : src/analysis.cc.s

src/control_and_verification.o: src/control_and_verification.cc.o

.PHONY : src/control_and_verification.o

# target to build an object file
src/control_and_verification.cc.o:
	$(MAKE) -f CMakeFiles/karst.dir/build.make CMakeFiles/karst.dir/src/control_and_verification.cc.o
.PHONY : src/control_and_verification.cc.o

src/control_and_verification.i: src/control_and_verification.cc.i

.PHONY : src/control_and_verification.i

# target to preprocess a source file
src/control_and_verification.cc.i:
	$(MAKE) -f CMakeFiles/karst.dir/build.make CMakeFiles/karst.dir/src/control_and_verification.cc.i
.PHONY : src/control_and_verification.cc.i

src/control_and_verification.s: src/control_and_verification.cc.s

.PHONY : src/control_and_verification.s

# target to generate assembly for a file
src/control_and_verification.cc.s:
	$(MAKE) -f CMakeFiles/karst.dir/build.make CMakeFiles/karst.dir/src/control_and_verification.cc.s
.PHONY : src/control_and_verification.cc.s

src/dissolution.o: src/dissolution.cc.o

.PHONY : src/dissolution.o

# target to build an object file
src/dissolution.cc.o:
	$(MAKE) -f CMakeFiles/karst.dir/build.make CMakeFiles/karst.dir/src/dissolution.cc.o
.PHONY : src/dissolution.cc.o

src/dissolution.i: src/dissolution.cc.i

.PHONY : src/dissolution.i

# target to preprocess a source file
src/dissolution.cc.i:
	$(MAKE) -f CMakeFiles/karst.dir/build.make CMakeFiles/karst.dir/src/dissolution.cc.i
.PHONY : src/dissolution.cc.i

src/dissolution.s: src/dissolution.cc.s

.PHONY : src/dissolution.s

# target to generate assembly for a file
src/dissolution.cc.s:
	$(MAKE) -f CMakeFiles/karst.dir/build.make CMakeFiles/karst.dir/src/dissolution.cc.s
.PHONY : src/dissolution.cc.s

src/evolution.o: src/evolution.cc.o

.PHONY : src/evolution.o

# target to build an object file
src/evolution.cc.o:
	$(MAKE) -f CMakeFiles/karst.dir/build.make CMakeFiles/karst.dir/src/evolution.cc.o
.PHONY : src/evolution.cc.o

src/evolution.i: src/evolution.cc.i

.PHONY : src/evolution.i

# target to preprocess a source file
src/evolution.cc.i:
	$(MAKE) -f CMakeFiles/karst.dir/build.make CMakeFiles/karst.dir/src/evolution.cc.i
.PHONY : src/evolution.cc.i

src/evolution.s: src/evolution.cc.s

.PHONY : src/evolution.s

# target to generate assembly for a file
src/evolution.cc.s:
	$(MAKE) -f CMakeFiles/karst.dir/build.make CMakeFiles/karst.dir/src/evolution.cc.s
.PHONY : src/evolution.cc.s

src/grain.o: src/grain.cc.o

.PHONY : src/grain.o

# target to build an object file
src/grain.cc.o:
	$(MAKE) -f CMakeFiles/karst.dir/build.make CMakeFiles/karst.dir/src/grain.cc.o
.PHONY : src/grain.cc.o

src/grain.i: src/grain.cc.i

.PHONY : src/grain.i

# target to preprocess a source file
src/grain.cc.i:
	$(MAKE) -f CMakeFiles/karst.dir/build.make CMakeFiles/karst.dir/src/grain.cc.i
.PHONY : src/grain.cc.i

src/grain.s: src/grain.cc.s

.PHONY : src/grain.s

# target to generate assembly for a file
src/grain.cc.s:
	$(MAKE) -f CMakeFiles/karst.dir/build.make CMakeFiles/karst.dir/src/grain.cc.s
.PHONY : src/grain.cc.s

src/import_export.o: src/import_export.cc.o

.PHONY : src/import_export.o

# target to build an object file
src/import_export.cc.o:
	$(MAKE) -f CMakeFiles/karst.dir/build.make CMakeFiles/karst.dir/src/import_export.cc.o
.PHONY : src/import_export.cc.o

src/import_export.i: src/import_export.cc.i

.PHONY : src/import_export.i

# target to preprocess a source file
src/import_export.cc.i:
	$(MAKE) -f CMakeFiles/karst.dir/build.make CMakeFiles/karst.dir/src/import_export.cc.i
.PHONY : src/import_export.cc.i

src/import_export.s: src/import_export.cc.s

.PHONY : src/import_export.s

# target to generate assembly for a file
src/import_export.cc.s:
	$(MAKE) -f CMakeFiles/karst.dir/build.make CMakeFiles/karst.dir/src/import_export.cc.s
.PHONY : src/import_export.cc.s

src/initial_modifications.o: src/initial_modifications.cc.o

.PHONY : src/initial_modifications.o

# target to build an object file
src/initial_modifications.cc.o:
	$(MAKE) -f CMakeFiles/karst.dir/build.make CMakeFiles/karst.dir/src/initial_modifications.cc.o
.PHONY : src/initial_modifications.cc.o

src/initial_modifications.i: src/initial_modifications.cc.i

.PHONY : src/initial_modifications.i

# target to preprocess a source file
src/initial_modifications.cc.i:
	$(MAKE) -f CMakeFiles/karst.dir/build.make CMakeFiles/karst.dir/src/initial_modifications.cc.i
.PHONY : src/initial_modifications.cc.i

src/initial_modifications.s: src/initial_modifications.cc.s

.PHONY : src/initial_modifications.s

# target to generate assembly for a file
src/initial_modifications.cc.s:
	$(MAKE) -f CMakeFiles/karst.dir/build.make CMakeFiles/karst.dir/src/initial_modifications.cc.s
.PHONY : src/initial_modifications.cc.s

src/main.o: src/main.cc.o

.PHONY : src/main.o

# target to build an object file
src/main.cc.o:
	$(MAKE) -f CMakeFiles/karst.dir/build.make CMakeFiles/karst.dir/src/main.cc.o
.PHONY : src/main.cc.o

src/main.i: src/main.cc.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cc.i:
	$(MAKE) -f CMakeFiles/karst.dir/build.make CMakeFiles/karst.dir/src/main.cc.i
.PHONY : src/main.cc.i

src/main.s: src/main.cc.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cc.s:
	$(MAKE) -f CMakeFiles/karst.dir/build.make CMakeFiles/karst.dir/src/main.cc.s
.PHONY : src/main.cc.s

src/merging.o: src/merging.cc.o

.PHONY : src/merging.o

# target to build an object file
src/merging.cc.o:
	$(MAKE) -f CMakeFiles/karst.dir/build.make CMakeFiles/karst.dir/src/merging.cc.o
.PHONY : src/merging.cc.o

src/merging.i: src/merging.cc.i

.PHONY : src/merging.i

# target to preprocess a source file
src/merging.cc.i:
	$(MAKE) -f CMakeFiles/karst.dir/build.make CMakeFiles/karst.dir/src/merging.cc.i
.PHONY : src/merging.cc.i

src/merging.s: src/merging.cc.s

.PHONY : src/merging.s

# target to generate assembly for a file
src/merging.cc.s:
	$(MAKE) -f CMakeFiles/karst.dir/build.make CMakeFiles/karst.dir/src/merging.cc.s
.PHONY : src/merging.cc.s

src/network.o: src/network.cc.o

.PHONY : src/network.o

# target to build an object file
src/network.cc.o:
	$(MAKE) -f CMakeFiles/karst.dir/build.make CMakeFiles/karst.dir/src/network.cc.o
.PHONY : src/network.cc.o

src/network.i: src/network.cc.i

.PHONY : src/network.i

# target to preprocess a source file
src/network.cc.i:
	$(MAKE) -f CMakeFiles/karst.dir/build.make CMakeFiles/karst.dir/src/network.cc.i
.PHONY : src/network.cc.i

src/network.s: src/network.cc.s

.PHONY : src/network.s

# target to generate assembly for a file
src/network.cc.s:
	$(MAKE) -f CMakeFiles/karst.dir/build.make CMakeFiles/karst.dir/src/network.cc.s
.PHONY : src/network.cc.s

src/network_generation.o: src/network_generation.cc.o

.PHONY : src/network_generation.o

# target to build an object file
src/network_generation.cc.o:
	$(MAKE) -f CMakeFiles/karst.dir/build.make CMakeFiles/karst.dir/src/network_generation.cc.o
.PHONY : src/network_generation.cc.o

src/network_generation.i: src/network_generation.cc.i

.PHONY : src/network_generation.i

# target to preprocess a source file
src/network_generation.cc.i:
	$(MAKE) -f CMakeFiles/karst.dir/build.make CMakeFiles/karst.dir/src/network_generation.cc.i
.PHONY : src/network_generation.cc.i

src/network_generation.s: src/network_generation.cc.s

.PHONY : src/network_generation.s

# target to generate assembly for a file
src/network_generation.cc.s:
	$(MAKE) -f CMakeFiles/karst.dir/build.make CMakeFiles/karst.dir/src/network_generation.cc.s
.PHONY : src/network_generation.cc.s

src/network_maintenance.o: src/network_maintenance.cc.o

.PHONY : src/network_maintenance.o

# target to build an object file
src/network_maintenance.cc.o:
	$(MAKE) -f CMakeFiles/karst.dir/build.make CMakeFiles/karst.dir/src/network_maintenance.cc.o
.PHONY : src/network_maintenance.cc.o

src/network_maintenance.i: src/network_maintenance.cc.i

.PHONY : src/network_maintenance.i

# target to preprocess a source file
src/network_maintenance.cc.i:
	$(MAKE) -f CMakeFiles/karst.dir/build.make CMakeFiles/karst.dir/src/network_maintenance.cc.i
.PHONY : src/network_maintenance.cc.i

src/network_maintenance.s: src/network_maintenance.cc.s

.PHONY : src/network_maintenance.s

# target to generate assembly for a file
src/network_maintenance.cc.s:
	$(MAKE) -f CMakeFiles/karst.dir/build.make CMakeFiles/karst.dir/src/network_maintenance.cc.s
.PHONY : src/network_maintenance.cc.s

src/node.o: src/node.cc.o

.PHONY : src/node.o

# target to build an object file
src/node.cc.o:
	$(MAKE) -f CMakeFiles/karst.dir/build.make CMakeFiles/karst.dir/src/node.cc.o
.PHONY : src/node.cc.o

src/node.i: src/node.cc.i

.PHONY : src/node.i

# target to preprocess a source file
src/node.cc.i:
	$(MAKE) -f CMakeFiles/karst.dir/build.make CMakeFiles/karst.dir/src/node.cc.i
.PHONY : src/node.cc.i

src/node.s: src/node.cc.s

.PHONY : src/node.s

# target to generate assembly for a file
src/node.cc.s:
	$(MAKE) -f CMakeFiles/karst.dir/build.make CMakeFiles/karst.dir/src/node.cc.s
.PHONY : src/node.cc.s

src/pattern_analysis.o: src/pattern_analysis.cc.o

.PHONY : src/pattern_analysis.o

# target to build an object file
src/pattern_analysis.cc.o:
	$(MAKE) -f CMakeFiles/karst.dir/build.make CMakeFiles/karst.dir/src/pattern_analysis.cc.o
.PHONY : src/pattern_analysis.cc.o

src/pattern_analysis.i: src/pattern_analysis.cc.i

.PHONY : src/pattern_analysis.i

# target to preprocess a source file
src/pattern_analysis.cc.i:
	$(MAKE) -f CMakeFiles/karst.dir/build.make CMakeFiles/karst.dir/src/pattern_analysis.cc.i
.PHONY : src/pattern_analysis.cc.i

src/pattern_analysis.s: src/pattern_analysis.cc.s

.PHONY : src/pattern_analysis.s

# target to generate assembly for a file
src/pattern_analysis.cc.s:
	$(MAKE) -f CMakeFiles/karst.dir/build.make CMakeFiles/karst.dir/src/pattern_analysis.cc.s
.PHONY : src/pattern_analysis.cc.s

src/pore.o: src/pore.cc.o

.PHONY : src/pore.o

# target to build an object file
src/pore.cc.o:
	$(MAKE) -f CMakeFiles/karst.dir/build.make CMakeFiles/karst.dir/src/pore.cc.o
.PHONY : src/pore.cc.o

src/pore.i: src/pore.cc.i

.PHONY : src/pore.i

# target to preprocess a source file
src/pore.cc.i:
	$(MAKE) -f CMakeFiles/karst.dir/build.make CMakeFiles/karst.dir/src/pore.cc.i
.PHONY : src/pore.cc.i

src/pore.s: src/pore.cc.s

.PHONY : src/pore.s

# target to generate assembly for a file
src/pore.cc.s:
	$(MAKE) -f CMakeFiles/karst.dir/build.make CMakeFiles/karst.dir/src/pore.cc.s
.PHONY : src/pore.cc.s

src/printing.o: src/printing.cc.o

.PHONY : src/printing.o

# target to build an object file
src/printing.cc.o:
	$(MAKE) -f CMakeFiles/karst.dir/build.make CMakeFiles/karst.dir/src/printing.cc.o
.PHONY : src/printing.cc.o

src/printing.i: src/printing.cc.i

.PHONY : src/printing.i

# target to preprocess a source file
src/printing.cc.i:
	$(MAKE) -f CMakeFiles/karst.dir/build.make CMakeFiles/karst.dir/src/printing.cc.i
.PHONY : src/printing.cc.i

src/printing.s: src/printing.cc.s

.PHONY : src/printing.s

# target to generate assembly for a file
src/printing.cc.s:
	$(MAKE) -f CMakeFiles/karst.dir/build.make CMakeFiles/karst.dir/src/printing.cc.s
.PHONY : src/printing.cc.s

src/printing_net.o: src/printing_net.cc.o

.PHONY : src/printing_net.o

# target to build an object file
src/printing_net.cc.o:
	$(MAKE) -f CMakeFiles/karst.dir/build.make CMakeFiles/karst.dir/src/printing_net.cc.o
.PHONY : src/printing_net.cc.o

src/printing_net.i: src/printing_net.cc.i

.PHONY : src/printing_net.i

# target to preprocess a source file
src/printing_net.cc.i:
	$(MAKE) -f CMakeFiles/karst.dir/build.make CMakeFiles/karst.dir/src/printing_net.cc.i
.PHONY : src/printing_net.cc.i

src/printing_net.s: src/printing_net.cc.s

.PHONY : src/printing_net.s

# target to generate assembly for a file
src/printing_net.cc.s:
	$(MAKE) -f CMakeFiles/karst.dir/build.make CMakeFiles/karst.dir/src/printing_net.cc.s
.PHONY : src/printing_net.cc.s

src/save_in_VTK.o: src/save_in_VTK.cc.o

.PHONY : src/save_in_VTK.o

# target to build an object file
src/save_in_VTK.cc.o:
	$(MAKE) -f CMakeFiles/karst.dir/build.make CMakeFiles/karst.dir/src/save_in_VTK.cc.o
.PHONY : src/save_in_VTK.cc.o

src/save_in_VTK.i: src/save_in_VTK.cc.i

.PHONY : src/save_in_VTK.i

# target to preprocess a source file
src/save_in_VTK.cc.i:
	$(MAKE) -f CMakeFiles/karst.dir/build.make CMakeFiles/karst.dir/src/save_in_VTK.cc.i
.PHONY : src/save_in_VTK.cc.i

src/save_in_VTK.s: src/save_in_VTK.cc.s

.PHONY : src/save_in_VTK.s

# target to generate assembly for a file
src/save_in_VTK.cc.s:
	$(MAKE) -f CMakeFiles/karst.dir/build.make CMakeFiles/karst.dir/src/save_in_VTK.cc.s
.PHONY : src/save_in_VTK.cc.s

src/setup.o: src/setup.cc.o

.PHONY : src/setup.o

# target to build an object file
src/setup.cc.o:
	$(MAKE) -f CMakeFiles/karst.dir/build.make CMakeFiles/karst.dir/src/setup.cc.o
.PHONY : src/setup.cc.o

src/setup.i: src/setup.cc.i

.PHONY : src/setup.i

# target to preprocess a source file
src/setup.cc.i:
	$(MAKE) -f CMakeFiles/karst.dir/build.make CMakeFiles/karst.dir/src/setup.cc.i
.PHONY : src/setup.cc.i

src/setup.s: src/setup.cc.s

.PHONY : src/setup.s

# target to generate assembly for a file
src/setup.cc.s:
	$(MAKE) -f CMakeFiles/karst.dir/build.make CMakeFiles/karst.dir/src/setup.cc.s
.PHONY : src/setup.cc.s

src/tests.o: src/tests.cc.o

.PHONY : src/tests.o

# target to build an object file
src/tests.cc.o:
	$(MAKE) -f CMakeFiles/karst.dir/build.make CMakeFiles/karst.dir/src/tests.cc.o
.PHONY : src/tests.cc.o

src/tests.i: src/tests.cc.i

.PHONY : src/tests.i

# target to preprocess a source file
src/tests.cc.i:
	$(MAKE) -f CMakeFiles/karst.dir/build.make CMakeFiles/karst.dir/src/tests.cc.i
.PHONY : src/tests.cc.i

src/tests.s: src/tests.cc.s

.PHONY : src/tests.s

# target to generate assembly for a file
src/tests.cc.s:
	$(MAKE) -f CMakeFiles/karst.dir/build.make CMakeFiles/karst.dir/src/tests.cc.s
.PHONY : src/tests.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... karst"
	@echo "... src/analysis.o"
	@echo "... src/analysis.i"
	@echo "... src/analysis.s"
	@echo "... src/control_and_verification.o"
	@echo "... src/control_and_verification.i"
	@echo "... src/control_and_verification.s"
	@echo "... src/dissolution.o"
	@echo "... src/dissolution.i"
	@echo "... src/dissolution.s"
	@echo "... src/evolution.o"
	@echo "... src/evolution.i"
	@echo "... src/evolution.s"
	@echo "... src/grain.o"
	@echo "... src/grain.i"
	@echo "... src/grain.s"
	@echo "... src/import_export.o"
	@echo "... src/import_export.i"
	@echo "... src/import_export.s"
	@echo "... src/initial_modifications.o"
	@echo "... src/initial_modifications.i"
	@echo "... src/initial_modifications.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/merging.o"
	@echo "... src/merging.i"
	@echo "... src/merging.s"
	@echo "... src/network.o"
	@echo "... src/network.i"
	@echo "... src/network.s"
	@echo "... src/network_generation.o"
	@echo "... src/network_generation.i"
	@echo "... src/network_generation.s"
	@echo "... src/network_maintenance.o"
	@echo "... src/network_maintenance.i"
	@echo "... src/network_maintenance.s"
	@echo "... src/node.o"
	@echo "... src/node.i"
	@echo "... src/node.s"
	@echo "... src/pattern_analysis.o"
	@echo "... src/pattern_analysis.i"
	@echo "... src/pattern_analysis.s"
	@echo "... src/pore.o"
	@echo "... src/pore.i"
	@echo "... src/pore.s"
	@echo "... src/printing.o"
	@echo "... src/printing.i"
	@echo "... src/printing.s"
	@echo "... src/printing_net.o"
	@echo "... src/printing_net.i"
	@echo "... src/printing_net.s"
	@echo "... src/save_in_VTK.o"
	@echo "... src/save_in_VTK.i"
	@echo "... src/save_in_VTK.s"
	@echo "... src/setup.o"
	@echo "... src/setup.i"
	@echo "... src/setup.s"
	@echo "... src/tests.o"
	@echo "... src/tests.i"
	@echo "... src/tests.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

